name: Docs

on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*'

permissions:
    contents: write

jobs:
  docs-gen:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pdoc3
          # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Pdoc build
        run: |
          export PYTHONPATH='/home/runner/work/Vehicle-Detection/Vehicle-Detection/src'
          pdoc3 --html src/ -o docs/ -f
          
      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          allow_empty_commit: true
          personal_token: ${{ secrets.DOCS_DEPLOY_TOKEN }}
          publish_branch: gh-pages
          publish_dir: docs/